# Generated by Django 4.2.23 on 2025-07-10 06:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('is_thumbnail', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapingProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=100)),
                ('url_pattern', models.CharField(max_length=255)),
                ('last_page_scraped', models.IntegerField(default=0)),
                ('total_properties', models.IntegerField(default=0)),
                ('last_scraped_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Scraping Progress',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='property',
        ),
        migrations.AlterUniqueTogether(
            name='propertyview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='propertyview',
            name='property',
        ),
        migrations.RemoveField(
            model_name='propertyview',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='savedproperty',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='savedproperty',
            name='property',
        ),
        migrations.RemoveField(
            model_name='savedproperty',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.AddField(
            model_name='property',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(default='Nairobi', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
        migrations.DeleteModel(
            name='PropertyView',
        ),
        migrations.DeleteModel(
            name='SavedProperty',
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='properties.property'),
        ),
        migrations.AddField(
            model_name='image',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property'),
        ),
        migrations.AddField(
            model_name='contact',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='properties.property'),
        ),
        migrations.AddField(
            model_name='property',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='properties.source'),
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('source', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='propertydetail',
            unique_together={('property', 'key')},
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(condition=models.Q(('is_thumbnail', True)), fields=('property',), name='unique_thumbnail_per_property'),
        ),
        migrations.RemoveField(
            model_name='property',
            name='address',
        ),
        migrations.RemoveField(
            model_name='property',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='features',
        ),
        migrations.RemoveField(
            model_name='property',
            name='furnished',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='property',
            name='landlord',
        ),
        migrations.RemoveField(
            model_name='property',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='parking_spaces',
        ),
        migrations.RemoveField(
            model_name='property',
            name='pets_allowed',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rent_amount',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rental_period',
        ),
        migrations.RemoveField(
            model_name='property',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='property',
            name='square_meters',
        ),
        migrations.RemoveField(
            model_name='property',
            name='status',
        ),
        migrations.RemoveField(
            model_name='property',
            name='utilities_included',
        ),
        migrations.DeleteModel(
            name='PropertyFeature',
        ),
    ]
