# Generated by Django 4.2.23 on 2025-10-08 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_contact_image_propertydetail_scrapingprogress_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_base_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='order_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='variant',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='card_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='detail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='first_seen_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='property',
            name='last_crawled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(fields=('property', 'image_base_id', 'variant'), name='unique_image_variant_per_property'),
        ),
    ]
