# Generated by Django 4.2.23 on 2025-10-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_image_image_base_id_image_order_index_image_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetail',
            name='value',
            field=models.CharField(max_length=2000),
        ),
    ]
