# Generated by Django 4.2.23 on 2025-12-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_propertydetail_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='detail_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
