# Generated by Django 4.2.23 on 2026-01-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order_index', 'id']},
        ),
        migrations.AddField(
            model_name='image',
            name='cleaned_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
