# Generated by Django 4.2.23 on 2026-01-15 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0007_alter_image_options_image_cleaned_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('referer', models.URLField(blank=True, max_length=500)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('is_login', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['-visited_at'], name='properties__visited_b3aa82_idx'), models.Index(fields=['ip_address', '-visited_at'], name='properties__ip_addr_14342b_idx'), models.Index(fields=['user', '-visited_at'], name='properties__user_id_8e8621_idx')],
            },
        ),
    ]
